name: Build & Publish APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "keystore/keystore.jks"
          encodedString: ${{ secrets.ENCODED_KEYSTORE }}
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node Modules
        run: npm install
      - name: Publish Release
        run: node scripts/release.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Commit
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "publish new build"
      - name: Push to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          force: true
